# Generated by Django 2.2.1 on 2019-06-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='Gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
