# Generated by Django 2.2.1 on 2019-06-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190611_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditemdata',
            name='item_type',
            field=models.CharField(choices=[('CARD', '校园卡'), ('BOOK', '书籍类'), ('ELEC', '电子产品'), ('OTHER', '其他')], default='其他', max_length=20),
        ),
        migrations.AddField(
            model_name='lostitemdata',
            name='item_type',
            field=models.CharField(choices=[('CARD', '校园卡'), ('BOOK', '书籍类'), ('ELEC', '电子产品'), ('OTHER', '其他')], default='其他', max_length=20),
        ),
    ]
