# Generated by Django 2.2.1 on 2019-06-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190613_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditemdata',
            name='item_description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='lostitemdata',
            name='item_description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
