# Generated by Django 2.2.1 on 2019-06-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190613_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditemdata',
            name='item_type',
            field=models.CharField(choices=[('CARD', '校园卡'), ('BOOK', '书籍类'), ('STUDY', '学习用品'), ('LIVE', '生活用品'), ('ELEC', '电子产品'), ('VAL', '贵重物品'), ('OTHER', '其他')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='lostitemdata',
            name='item_type',
            field=models.CharField(choices=[('CARD', '校园卡'), ('BOOK', '书籍类'), ('STUDY', '学习用品'), ('LIVE', '生活用品'), ('ELEC', '电子产品'), ('VAL', '贵重物品'), ('OTHER', '其他')], default='', max_length=20),
        ),
    ]
